apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: risk-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: hadoop-demo
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: risk-ui
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: risk-engine
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: hadoop-demo
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: risk-engine
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stream-ingestor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: hadoop-demo
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: stream-ingestor
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
