---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: risk-ui-prod
  namespace: argocd
spec:
  project: hadoop-demo
  source:
    repoURL: "git@bitbucket.company.internal:devops/hadoop-demo-gitops.git"
    targetRevision: HEAD
    path: helm/risk-ui
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hadoop-demo-prod
  syncPolicy:
    # prod: manual sync only — no automated sync
    syncOptions:
      - CreateNamespace=true
