# SOURCE: helm/report-generator/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: kube-demo-report-generator
  namespace: kube-demo
  labels:
    helm.sh/chart: report-generator-0.1.0
    app.kubernetes.io/name: report-generator
    app.kubernetes.io/instance: kube-demo
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@kube-demo-postgresql:5432/orders"
