# SOURCE: helm/notification-service/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: kube-demo-notification-service
  namespace: kube-demo
  labels:
    helm.sh/chart: notification-service-0.1.0
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/instance: kube-demo
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  RABBITMQ_URL: "amqp://user:password@kube-demo-rabbitmq:5672/"
