apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oracle-reporter.fullname" . }}
  labels:
    {{- include "oracle-reporter.labels" . | nindent 4 }}
automountServiceAccountToken: false
