apiVersion: v1
kind: Service
metadata:
  name: {{ include "stream-ingestor.fullname" . }}
  labels:
    {{- include "stream-ingestor.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: stream-ingestor
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
