apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stream-ingestor.fullname" . }}
  labels:
    {{- include "stream-ingestor.labels" . | nindent 4 }}
automountServiceAccountToken: false
